version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pokemon_exchange
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
